using CairoMakie
using Dates
using DelimitedFiles
using Statistics

# Recreates exactly Figures 1--5 specified in the application tables-and-figures prompt.
# Inputs are the source price file and the rolling forecasts generated by applications_crypto.jl.

const ROOT = abspath(joinpath(@__DIR__, ".."))
const DATA = joinpath(ROOT, "data", "crypto_data.csv")
const FORECASTS = joinpath(ROOT, "output", "applications", "rolling_risk_forecasts.csv")
const OUT = joinpath(ROOT, "output", "applications", "paper_figures")
const ASSETS = ["BNB", "BTC", "ETH", "EUR"]
const TICKERS = Dict("BNB-USD"=>"BNB", "BTC-USD"=>"BTC", "ETH-USD"=>"ETH", "EURUSD=X"=>"EUR")
const NAMES = ["figure_1_exchange_rates", "figure_2_drawdowns", "figure_3_conditional_tail_risk", "figure_4_interval_width_ratios", "figure_5_capital_buffers"]
const PALETTES = Dict(:color=>(returns="#333333",xp="#0072B2",var="#E69F00",es="#CC3311",axis="#303030"), :bw=>(returns="#222222",xp="#666666",var="#A0A0A0",es="#000000",axis="#303030"))

struct AssetData
    name::String
    dates::Vector{Date}
    prices::Vector{Float64}
end
struct Forecast
    date::Date
    realized::Float64
    var::Float64
    var_lo::Float64
    var_hi::Float64
    es::Float64
    es_lo::Float64
    es_hi::Float64
    xp::Float64
    xp_lo::Float64
    xp_hi::Float64
    tau::Float64
end

datevalue(d::Date) = Float64(Dates.value(d))
finitevalues(x) = [Float64(v) for v in x if isfinite(v)]

function readcsv(path)
    raw, header = readdlm(path, ',', String; header=true)
    return raw, Dict(String(h)=>i for (i,h) in enumerate(vec(header)))
end
function cell(raw, index, row, name)
    value = strip(raw[row, index[name]])
    isempty(value) ? NaN : parse(Float64, value)
end
function read_assets()
    raw, i = readcsv(DATA)
    grouped = Dict(asset=>Tuple{Date,Float64}[] for asset in ASSETS)
    for r in axes(raw,1)
        ticker = raw[r,i["ticker"]]
        haskey(TICKERS,ticker) || continue
        price = cell(raw,i,r,"price_adjusted")
        isfinite(price) && price > 0 || continue
        push!(grouped[TICKERS[ticker]], (Date(raw[r,i["ref_date"]]),price))
    end
    return [begin x=sort(grouped[a];by=first); AssetData(a,first.(x),last.(x)) end for a in ASSETS]
end
function read_forecasts()
    raw, i = readcsv(FORECASTS)
    required = ("realized_return","var","var_lo","var_hi","es_01","es_01_lo","es_01_hi","xp_fixed","xp_fixed_lo","xp_fixed_hi","tau_alpha","ci_level")
    all(haskey(i,name) for name in required) || error("Forecast CSV lacks the 1% ES / fixed 1% XP outputs. Re-run applications_crypto.jl.")
    level = unique(cell(raw,i,r,"ci_level") for r in axes(raw,1))
    length(level) == 1 && isapprox(only(level),.95;atol=1e-10) || error("The paper figures require 95% CLT intervals.")
    result = Dict(a=>Forecast[] for a in ASSETS)
    for r in axes(raw,1)
        a=raw[r,i["ticker"]]; haskey(result,a) || continue
        push!(result[a], Forecast(Date(raw[r,i["date"]]),cell(raw,i,r,"realized_return"),cell(raw,i,r,"var"),cell(raw,i,r,"var_lo"),cell(raw,i,r,"var_hi"),cell(raw,i,r,"es_01"),cell(raw,i,r,"es_01_lo"),cell(raw,i,r,"es_01_hi"),cell(raw,i,r,"xp_fixed"),cell(raw,i,r,"xp_fixed_lo"),cell(raw,i,r,"xp_fixed_hi"),cell(raw,i,r,"tau_alpha")))
    end
    foreach(x->sort!(x;by=f->f.date),values(result))
    return result
end
function annual_ticks(firstdate,lastdate)
    dates=[Date(y,1,1) for y in year(firstdate):year(lastdate) if firstdate<=Date(y,1,1)<=lastdate]
    return datevalue.(dates),string.(year.(dates))
end
function panel(parent;ticks=nothing,showx=true)
    Axis(parent;xticks=ticks,xticklabelsvisible=showx,xlabel="",ylabel="",xgridvisible=false,
         ygridcolor=("#D9DDE1",.85),leftspinecolor="#444444",rightspinecolor="#444444",topspinecolor="#444444",bottomspinecolor="#444444",xticklabelsize=14,yticklabelsize=14)
end
function savefigure(fig,name,mode)
    save(joinpath(OUT,"$(name)_$(mode).pdf"),fig)
end
function drawdowns(prices)
    peak=first(prices)
    return [begin peak=max(peak,p); p/peak-1 end for p in prices]
end
function qtile(values,p)
    x=sort(values); h=1+(length(x)-1)*p; lo=floor(Int,h); hi=ceil(Int,h)
    return lo==hi ? x[lo] : x[lo]+(h-lo)*(x[hi]-x[lo])
end
function boxplot!(ax,x,values,color;width=.28)
    q1,q2,q3=qtile(values,.25),qtile(values,.5),qtile(values,.75); iqr=q3-q1
    low=max(minimum(values),q1-1.5*iqr); high=min(maximum(values),q3+1.5*iqr); outs=[v for v in values if v<low || v>high]
    isempty(outs) || scatter!(ax,x .+ .05 .* sin.(2.4 .* eachindex(outs)),outs;color=(color,.18),markersize=5,strokewidth=0)
    poly!(ax,Point2f[(x-width/2,q1),(x+width/2,q1),(x+width/2,q3),(x-width/2,q3)];color=(color,.55),strokecolor="#404040",strokewidth=1.1)
    lines!(ax,[x,x],[low,q1];color="#404040"); lines!(ax,[x,x],[q3,high];color="#404040")
    lines!(ax,[x-width/5,x+width/5],[low,low];color="#404040"); lines!(ax,[x-width/5,x+width/5],[high,high];color="#404040")
    lines!(ax,[x-width/2,x+width/2],[q2,q2];color="#202020",linewidth=2)
end

function figure1(assets,mode)
    pal=PALETTES[mode]; fig=Figure(size=(1600,1120),fontsize=18,backgroundcolor=:white)
    start,stop=Date(2016,1,1),Date(2023,12,31); limits=Dict("BNB"=>(0.,750.),"BTC"=>(0.,75000.),"ETH"=>(0.,5200.),"EUR"=>(.9,1.3))
    for (n,a) in enumerate(assets)
        row=(n-1)÷2+1;
        col=(n-1)%2+1;
        ax=panel(fig[row,col];ticks=annual_ticks(start,stop),showx=row==2)
        xlims!(ax,datevalue(start),datevalue(stop));
        ylims!(ax,limits[a.name]...);
        lines!(ax,datevalue.(a.dates),a.prices;color=pal.xp,linewidth=1.8)
        text!(ax,.97,.94;text=a.name,space=:relative,align=(:right,:top),fontsize=20,font=:bold,color=pal.axis)
    end
    rowgap!(fig.layout,14); colgap!(fig.layout,18); savefigure(fig,NAMES[1],mode)
end
function figure2(assets,mode)
    pal=PALETTES[mode]; fig=Figure(size=(1200,820),fontsize=18,backgroundcolor=:white); ax=panel(fig[1,1];ticks=(1:4,ASSETS))
    start,stop=Date(2018,1,1),Date(2023,12,31)
    dd=[drawdowns([a.prices[i] for i in eachindex(a.dates) if start<=a.dates[i]<=stop]) for a in assets]
    ylims!(ax,minimum(minimum,dd)*1.05,.02); for (n,x) in enumerate(dd); boxplot!(ax,n,x,pal.xp;width=.48); end; xlims!(ax,.45,4.55)
    savefigure(fig,NAMES[2],mode)
end
function figure3(forecasts,mode)
    pal=PALETTES[mode]; fig=Figure(size=(1800,1900),fontsize=17,backgroundcolor=:white)
    start=first(forecasts["BTC"]).date; stop=minimum(last(forecasts[a]).date for a in ASSETS); ticks=annual_ticks(start,stop)
    for (row,a) in enumerate(ASSETS)
        fs=[f for f in forecasts[a] if start<=f.date<=stop]; dates=datevalue.([f.date for f in fs]); left=panel(fig[row,1];ticks=ticks,showx=row==4); right=panel(fig[row,2];ticks=ticks,showx=row==4)
        y=finitevalues(vcat([f.realized for f in fs],[f.xp for f in fs],[f.var for f in fs],[f.es for f in fs])); lo,hi=extrema(y); pad=max(.05*(hi-lo),.1); ylims!(left,lo-pad,hi+pad)
        lines!(left,dates,[f.realized for f in fs];color=(pal.returns,.7),linewidth=.75); lines!(left,dates,[f.xp for f in fs];color=pal.xp,linewidth=2); lines!(left,dates,[f.var for f in fs];color=pal.var,linewidth=1.8); lines!(left,dates,[f.es for f in fs];color=pal.es,linewidth=2)
        tau=100 .* [f.tau for f in fs]; ylims!(right,0,maximum(tau)*1.08); lines!(right,dates,tau;color=pal.returns,linewidth=1.5)
        text!(left,.02,.94;text=a,space=:relative,align=(:left,:top),fontsize=19,font=:bold,color=pal.axis)
    end
    Legend(fig[5,1:2],[LineElement(color=pal.returns,linewidth=2),LineElement(color=pal.xp,linewidth=3),LineElement(color=pal.var,linewidth=3),LineElement(color=pal.es,linewidth=3)],["Return","XP","VaR","ES"];orientation=:horizontal,framevisible=false,labelsize=17)
    colsize!(fig.layout,1,Relative(2/3)); colsize!(fig.layout,2,Relative(1/3)); rowgap!(fig.layout,12); savefigure(fig,NAMES[3],mode)
end
function figure4(forecasts,mode)
    pal=PALETTES[mode]; fig=Figure(size=(1200,850),fontsize=18,backgroundcolor=:white); ax=panel(fig[1,1];ticks=(1:4,ASSETS)); ratios=Dict{String,Tuple{Vector{Float64},Vector{Float64}}}()
    for a in ASSETS
        xpvar=Float64[]; xpes=Float64[]
        for f in forecasts[a]
            xp=f.xp_hi-f.xp_lo; var=f.var_hi-f.var_lo; es=f.es_hi-f.es_lo
            isfinite(xp)&&isfinite(var)&&isfinite(es)&&xp>0&&var>0&&es>0 || continue
            push!(xpvar,xp/var); push!(xpes,xp/es)
        end
        isempty(xpvar) && error("No valid XP/VaR interval ratios for $(a)."); isempty(xpes) && error("No valid XP/ES interval ratios for $(a)."); ratios[a]=(xpvar,xpes)
    end
    allvalues=vcat([vcat(ratios[a]...) for a in ASSETS]...); ylims!(ax,0,maximum(allvalues)*1.07); hlines!(ax,[1];color=pal.axis,linestyle=:dash)
    for (n,a) in enumerate(ASSETS); one,two=ratios[a]; boxplot!(ax,n-.18,one,pal.var;width=.3); boxplot!(ax,n+.18,two,pal.es;width=.3); end
    xlims!(ax,.45,4.55); Legend(fig[2,1],[PolyElement(color=(pal.var,.55),strokecolor="#404040"),PolyElement(color=(pal.es,.55),strokecolor="#404040")],["XP / VaR","XP / ES"];orientation=:horizontal,framevisible=false,labelsize=17)
    savefigure(fig,NAMES[4],mode)
end
function figure5(forecasts,mode)
    pal=PALETTES[mode]; fig=Figure(size=(1200,850),fontsize=18,backgroundcolor=:white); ax=panel(fig[1,1];ticks=(1:4,ASSETS)); buffers=Dict{String,Tuple{Vector{Float64},Vector{Float64},Vector{Float64}}}()
    for a in ASSETS
        fs=forecasts[a]
        buffers[a]=([f.realized-f.var for f in fs if isfinite(f.realized)&&isfinite(f.var)],[f.realized-f.es for f in fs if isfinite(f.realized)&&isfinite(f.es)],[f.realized-f.xp for f in fs if isfinite(f.realized)&&isfinite(f.xp)])
    end
    allvalues=vcat([vcat(buffers[a]...) for a in ASSETS]...); lo,hi=extrema(allvalues); pad=.07*(hi-lo); ylims!(ax,lo-pad,hi+pad); hlines!(ax,[0];color=pal.axis,linestyle=:dash)
    for (n,a) in enumerate(ASSETS); var,es,xp=buffers[a]; boxplot!(ax,n-.22,var,pal.var;width=.26); boxplot!(ax,n,es,pal.es;width=.26); boxplot!(ax,n+.22,xp,pal.xp;width=.26); end
    xlims!(ax,.45,4.55); Legend(fig[2,1],[PolyElement(color=(pal.var,.55),strokecolor="#404040"),PolyElement(color=(pal.es,.55),strokecolor="#404040"),PolyElement(color=(pal.xp,.55),strokecolor="#404040")],["VaR","ES","XP"];orientation=:horizontal,framevisible=false,labelsize=17)
    savefigure(fig,NAMES[5],mode)
end
function main()
    CairoMakie.activate!(); mkpath(OUT)
    for name in NAMES, mode in (:color,:bw);
        rm(joinpath(OUT,"$(name)_$(mode).pdf"),force=true);
    end
    assets=read_assets();
    forecasts=read_forecasts()
    for mode in (:color,:bw);
        figure1(assets,mode);
        figure2(assets,mode);
        figure3(forecasts,mode);
        figure4(forecasts,mode);
        figure5(forecasts,mode); end
    println("Recreated Figures 1--5 as vector PDFs in ",OUT)
end
abspath(PROGRAM_FILE) == abspath(@__FILE__) && main()
